language: node_js
node_js:
  - "node"
addons:
  firefox: "latest"
install:
  - npm install
  - npm install -g gulp
  - npm install -g karma
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp js-static-analysis
  - gulp build
  - $(npm bin)/karma start ./karma.conf.js --single-run --browsers Firefox