language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g gulp
  - npm install -g karma
script:
  - gulp js-static-analysis
  - gulp build
  - karma start ./karma.conf.js --single-run --browsers Firefox